name: Build and Deploy
on:
  push:
    branches:
      - '*/main'

jobs:
  build-and-deploy:
    env:
      MOD_VERSION: $(cat gradle.properties | grep mod_version)
      BRANCH_PREFIX: $(cat gradle.properties | grep mod_version | cut -d'+' -f2)
    strategy:
      matrix:
        java: [
          17,
        ]
    runs-on: ubuntu-latest
    steps:
      - name: check environment variables
        run: env
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        run: ./gradlew build
      - name: capture build artifacts
        if: |
          ${{ matrix.java == '17' }}
          github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: attempt modrinth upload
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          modrinth-id: wFyCClLQ
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          modrinth-dependencies: |
            fabric-api | depends | *
          # Modrinth has issues accepting javadocs right now
          #modrinth-files-secondary: build/libs/*-sources.jar

          version: "${{env.MOD_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.BRANCH_VERSION}}"
          java: "${{matrix.java}}"

      - name: deploy with mc-publish
        if: github.ref == 'refs/heads/${{ env.BRANCH_PREFIX }}/main'
        run: echo "Testing.."
        #uses: Kir-Antipov/mc-publish@v3.2
        #with:
          #modrinth-id: wFyCClLQ
          #modrinth-token: "${{secrets.MODRINTH_TOKEN}}"
          #modrinth-dependencies: |
          #  P7dR8mSH | depends | *
          # Modrinth has issues accepting javadocs right now
          #modrinth-files-secondary: build/libs/*-sources.jar

          #curseforge-id: 514734
          #curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          #curseforge-dependencies: |
          #  fabric-api | depends | *
          #curseforge-files-secondary: build/libs/*-@(sources\|javadoc).jar

          #github-tag: ${{ env.MOD_VERSION }}
          #github-token: ${{ secrets.REPOSITORY_TOKEN }}
          #github-commitish: ${{ env.BRANCH_PREFIX }}/main
          #github-files-secondary: build/libs/*-@(sources\|javadoc).jar

          #version: "${{env.MOD_VERSION}}"
          #version-type: release
          #changelog-file: CHANGELOG.md

          #loaders: fabric
          #game-versions: "${{env.BRANCH_VERSION}}"
          #java: "${{matrix.java}}"