name: Deploy
on:
  pull_request:
    types:
      - closed

env: 
  BRANCH_PREFIX: $(cat gradle.properties | grep mod_version | cut -d'+' -f2)
# test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check workflow runs
        run: echo "Workflow Running"
      - name: check branch
        if: ${{ github.ref == format('refs/heads/{0}/main', env.BRANCH_PREFIX) }}
        run: echo "CHECK-1=${{ github.ref == 'refs/heads/1.19.2/main' }}; Check-2=${{ github.ref }}"